### ISSUE TITLE
Help to adapt your driver to a Ricoh SP211?

### ISSUE THREAD

**Issue by jasvazquez** [madlynx/ricoh-sp100#63]
Hi Serge

I have bought two Ricoh SP 211 printers for my school but we can't use them with Linux.

I've installed your drivers (thanks) in different linux distros with no luck.

In a virtualbox (using the host usb port) the printer can be used without problems.

Trying to retrieve [the "control codes"](https://github.com/madlynx/ricoh-sp100/blob/master/pstoricohddst-gdi#L78) I've:
1. simulated it (using CUPS) on my linux host
1. installed the Ricoh Windows drivers on the virtualbox guest (bridged adapter)
1. added the cups printer in Windows as a shared printer
1. used tcpdump to log all the comunication among guest and host pcs

But I couldn't retrieve the codes expected.

Can you give me some clue (or webpage with info about how to do it) to learn the right way to retrieve the info I'm looking for.

Thanks for your attention and contribution to the comunity 👏👍

**Comment by aadityabagga** [comment]
https://github.com/madlynx/ricoh-sp100/pull/64

**Comment by grinya007** [comment]
Guys, I've just found official Mac OS driver for SP 211 printer on official Ricoh website, it's either some complicated marketing strategy (say, they pretend that this cheap printer is for Windows only to force Mac users buy more expensive models), or just silly mistake of someone responsible for publishing of drivers on website. Either way, long story short: do google for "ricoh sp 221 driver" -> follow first link -> choose Mac OS -> install driver from downloaded dmg -> choose "RICOH SP 221" driver upon installation (important here is not to choose drivers for ...N, ...w, ...Nw and such printers, all Ricoh printers with network connectivity are PCL printers, whereas this one is GDI, they call it DDST whatever that means). You'll find working driver for Linux there as well. And one more funny fact - it turns out that SP 221 model just doesn't exist at all =) really, try order it somewhere. Hope that helps, enjoy!

**Comment by nasdak** [comment]
Hey !
I just tried it on linux... IT WORKS ! thanks dude !!!! just choose SP221 :)

**Comment by jasvazquez** [comment]
Thx to everybody... it works! 👍

**Comment by acupofcode** [comment]
Oh my Gosh, grinya007 THANK YOU, SOOO much!
from the deep of my heart and nervous system. Thank you, GREAT!

**Comment by stozinho** [comment]
grinya007 works! thanks a lot
